### ISSUE TITLE
Private Profile Issue

### ISSUE THREAD

**Issue by Vekter000** [Bio2hazard/SteamCompletionist#11]
I am getting a "This profile is private." error message after logging in with my own Steam account as of last night. I set the new Steam profile security features to Public but that did not fix the issue. I think I set my SteamCompletionist profile to private so that might be the cause. 

My SteamCompletionist profile number is 76561198000805128.

**Comment by enesfarukmeniz** [comment]
You are not able to login SC, so you are trying to see your profile as anonymous and can't see it since it is private.
The reason you are not able to login SC is not related to new steam profile settings. I contacted Bio2hazard about "not able to login" issue 3 days ago, he said he will fix it this week :)

**Comment by Bio2hazard** [comment]
Fixed. Thanks Vekter, Enes and Reforced! Good catch!
