### ISSUE TITLE
Site has been down for a couple of weeks

### ISSUE THREAD

**Issue by primapresto** [Bio2hazard/SteamCompletionist#15]
Hey,
Is the site dead now?
It has been down for at least two weeks now, and only shows "It works!"

**Comment by mrougeau-trendsic** [comment]
Bump....site still down.

**Comment by Xerxes-77** [comment]
Please bring it back. The site is the best of its kind for me - a direct, simple and pleasing way to explore one's own catalog and keep track of progress.

**Comment by SpoonOfDoom** [comment]
@Bio2hazard - if you're not interested in hosting this anymore, could you share some details about what kind of traffic you usually had, what the costs were etc? If it's not too wild, I could maybe take over hosting, if you agree.

**Comment by Sininini** [comment]
I also really miss the site

**Comment by Bio2hazard** [comment]
It's back! @Sininini @SpoonOfDoom @primapresto @Blackbird88 @Distec00 and @Xerxes-77

Please take a look and let me know if you find anything that isn't working quite right. Sorry about the delay. On the bright side, it should be much more stable going forward.
The host had come under attack from random vulnerability scans and while it wasn't compromised, the logs filled up the disk space and the host died. I cleaned up the logs, but apache2 straight up refused to start up. Recovery was painful because it was a 10 year old server and basically nothing was working. I'd google an error and the results were not applicable because the software is so outdated. After spending way too much time on trying to fix it on the old host, I made backups and nuked everything.

So now it's running on modern software and hardware, has disk space alerts and monitoring and all that good stuff 👍

**Comment by Sininini** [comment]
Yay! Thank you so much for getting it back online!

**Comment by Xerxes-77** [comment]
Great news, thanks so much!

**Comment by Distec00** [comment]
Much appreciated! There are several other 'backlog managers' available for Steam, but I honestly find them to be too bloated and/or slow to navigate. Yours is concise and snappy, and was perfect for filtering my game queue!

**Comment by primapresto** [comment]
Thank you so much for spending time getting the site up and running again :)
